### ISSUE TITLE
uteshevia does not respond in Telegram

### ISSUE THREAD

**Issue by gkorepanov** [uteshevia/toolkitex#1]
He does make commits and is online in Telegram, but doesn't respond. Please, fix this.

**Comment by uteshevia** [comment]
Seems to be done.

I do not really think that an insult is a cause for opening such an issue.
Explain yourself.

![screenshot_20170222-210914](https://cloud.githubusercontent.com/assets/24862417/23225642/a872d580-f943-11e6-8fdb-7f2f42e9a746.jpg)
