### ISSUE TITLE
Switch to Python

### ISSUE THREAD

**Issue by gkorepanov** [uteshevia/toolkitex#13]
As the complexity of the script grows, using bash is becoming more and more bulky way to express its functionality. I believe that when we have crossed the point of parameters parsing, we should at least use the language with some parameters parsing package available. As we are stick to Python in a way, I believe it will be the best way to go.

**Comment by uteshevia** [comment]
In which cases would this make life easier?

**Comment by gkorepanov** [comment]
The code will be incomparably more laconic, more maintainable and readable.

**Comment by gkorepanov** [comment]
You will likely want to add presets functionality and some even more sophisticated things, and it will be quite time-consuming to dela with Bash.

**Comment by uteshevia** [comment]
I do not really feel the need to rewrite the code again since it's not clear in which way it may further develop. I can't even imagine what else should be implemented there.

**Comment by gkorepanov** [comment]
It's up to you.

**Comment by uteshevia** [comment]
You could suggest something that really suits the criteria of "necessarity" and "easier to implement in Python".
