### ISSUE TITLE
Writex enhancements

### ISSUE THREAD

**Issue by uteshevia** [uteshevia/toolkitex#3]
- [ ] Isolate the document template and default `.gitignore` built into the code of [`writex.sh`](https://github.com/uteshevia/toolkitex/blob/master/core/writex.sh).
- [ ] Fix Ubuntu-specific [code](https://github.com/uteshevia/toolkitex/blob/master/core/writex.sh#L10) in the "already exists" clause.
- [ ] Alter `unknown` to `unsupported` in the corresponding error [message](https://github.com/uteshevia/toolkitex/blob/master/core/writex.sh#L32).
- [ ] Add the possibility to set `writex` behavior, for instance, to choose whether to execute `git init`.

**Comment by gkorepanov** [comment]
I still don't have the hot buttons working after opening with `writex`

**Comment by uteshevia** [comment]
How does it work *in the wild*, while executed these two commands?
```
$ texmaker <file>.tex
$ xdg-open <file>.tex
```

**Comment by uteshevia** [comment]
How does it work *in the wild*, while executed these three commands?
```
$ texmaker <file>.tex
$ env UBUNTU_MENUPROXY= texmaker <file>.tex
$ xdg-open <file>.tex
```

If it does work when launched from app menu, what have you done to make it work this way?

**Comment by gkorepanov** [comment]
Can't check, I have left my charger in Sochi so don't have an access to my laptop.

**Comment by uteshevia** [comment]
The first task seems to be smoothly played down by using heredoc syntax.
