### ISSUE TITLE
Project documentation

### ISSUE THREAD

**Issue by uteshevia** [uteshevia/toolkitex#4]
The existing `README` does not provide a clear understanding of what exactly the project is and how to use it appropriately and comfortably. This particularly affects the package `iunits` and (possible) customization capabilities.

Thus,
- [ ] `README.md` needs to be completely redone.
- [ ] The docs set is to be written in Russian as well.

**Comment by gkorepanov** [comment]
The current readme is in bearable state though we should add the particular examoles of usage + most common patterns like redefining geometry or lists margins so as not to google for them frok time to time.

**Comment by uteshevia** [comment]
`README.md` updated in accordance to the changes applied.
Not sure if Russian version is relevant.

I strongly believe that the documentation should be more explicit and definitely more thorough.

**Comment by uteshevia** [comment]
Still, I am sure there will be further more impressive shifts coming to v2.
Have to return here later.
